---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    # - port: 80
    - port: 9292
      nodePort: 32092
      protocol: TCP
      targetPort: 9292
  selector:
    app: reddit
    component: ui
